apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The Petstore API
  links:
    - url: https://red-gate.com
      title: Redgate
      icon: dashboard
spec:
  type: openapi
  lifecycle: production
  owner: petstore@example.com
  definition:
    $text: http://localhost:16280/swagger/v1/swagger.json