apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The Petstore API
spec:
  type: openapi
  lifecycle: production
  owner: petstore@example.com
  definition:
    $text: https://localhost:44344/swagger/v1/swagger.json
backend:
  reading:
    allow:
      - host: localhost
      - host: 'localhost*'