apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: WeatherApp
  description: Mobile Weather App
  annotations:
    github.com/project-slug: asydikov/weather-forecast
    backstage.io/techdocs-ref: dir:.
spec:
  type: mobile
  lifecycle: production
  owner: kubernaughts
  system: test-system
  dependsOn:
    - resource:weather-forecast
  consumesApis:
    - weather-forecast