name: Print Default Env Variables For Different runners(machines)
on: [workflow_dispatch]
jobs:
  ubuntu_var_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: printdefualtvariablesubuntu
        run: echo ${env:GITHUB_RUN_ID}
                  ${env:GITHUB_RUN_NUMBER}
  macos_var_test_job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: printdefualtvariablesmacos
        run: echo ${env:GITHUB_RUN_ID}
                  ${env:GITHUB_RUN_NUMBER}
  windows_var_test_job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: printdefualtvariableswindows
        run: echo ${env:GITHUB_RUN_ID}
                  ${env:GITHUB_RUN_NUMBER}
